### ISSUE TITLE
Error (or at least confusion) in bandits code

### ISSUE THREAD

**Issue by zsunberg** [sisl/aa228-notebook#13]
The (excellent) bandits notebook plots learning curves, but I think there is a mistake in the code.

To plot a conventional learning curve, I think this line: https://github.com/sisl/aa228-notebook/blob/a33ec9d5d8d97e42d2f56801ec849e7e3f8b002a/bandits.jl#L82

Should just be
```
wins[step] = win
```

**Comment by mykelk** [comment]
I think so. Feel free to do a PR. Thanks!

**Comment by zsunberg** [comment]
I changed it and used it in class today. PR is #14. Is it OK if I go ahead and merge it? (I'm not sure if you still use these since the last commit was in 2019, ha)

**Comment by mykelk** [comment]
Great! You can go ahead an merge whatever you want on these! They would certainly benefit from a refresh.
